In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model, datasets
from sklearn.model_selection import train_test_split


# import some data to play with
iris = datasets.load_iris()
X = iris.data[:, :2]  # we only take the first two features.
Y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

X_train.shape, y_train.shape

((120, 2), (120,))

In [16]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
model = Pipeline([('poly', PolynomialFeatures(degree=2)),
                  ('linear', linear_model.LogisticRegression(fit_intercept=False))])
result = model.fit(X_train, y_train)

In [17]:
result.named_steps['linear'].coef_

array([[ 0.37052804,  0.87495095,  0.67576407, -0.88703761,  0.56431284,
         0.97587475],
       [ 0.15145275,  1.11891507, -0.0700449 , -0.33881532,  1.03586181,
        -1.52662987],
       [-0.48943342, -1.32436234, -0.75360699,  0.05959038,  0.89361376,
        -0.88261994]])

In [18]:
result.named_steps['poly'].powers_

array([[0, 0],
       [1, 0],
       [0, 1],
       [2, 0],
       [1, 1],
       [0, 2]])

In [21]:
result.named_steps['poly'].fit_transform(X_train)[:,5]

array([  9.  ,   9.  ,   6.25,   7.84,   7.84,  13.69,   5.29,  11.56,
         7.84,   6.25,   9.  ,  12.25,   4.84,   8.41,   8.41,   6.76,
        14.44,  12.96,   9.  ,   7.29,  11.56,  12.25,  14.44,   9.61,
         8.41,   7.84,   7.84,  11.56,   7.84,   9.  ,  11.56,   6.25,
         7.29,   9.  ,  10.24,   9.  ,  11.56,   9.  ,  10.24,   9.61,
         7.84,  10.89,   9.  ,  14.44,   4.84,   8.41,   9.  ,   5.29,
        10.89,   6.25,  13.69,   9.61,  16.81,  10.89,   9.  ,   7.29,
         7.29,   9.  ,  12.25,  10.89,   7.29,   9.61,   7.84,   8.41,
         9.  ,   9.  ,   5.29,  11.56,  12.96,   8.41,  19.36,   7.29,
         5.29,   5.76,   9.61,  11.56,   7.84,  12.25,  11.56,  11.56,
         7.84,  10.24,  10.89,  13.69,  10.24,   9.61,   7.29,   9.61,
         9.  ,   6.25,  10.24,  10.24,   9.  ,   9.  ,   8.41,   5.76,
         4.  ,  12.25,   9.  ,   5.76,  12.96,   9.  ,   8.41,  11.56,
         9.61,   8.41,   4.84,  10.24,   7.29,  11.56,   9.  ,   6.76,
      